name: Webapp CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}  
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}  
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}                
          DB_PORT: ${{ secrets.DB_PORT }}                   
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}           
        run: npm test

      - name: Build the application
        run: npm run build

      - name: Start the application
        env:
          DB_HOST:  ${{ secrets.DB_HOST }}                  
          DB_PORT:  ${{ secrets.DB_PORT }}             
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}
        run: |
          npm start &
          echo "Waiting for the application to start..."
          sleep 10  # Adjust sleep time based on how long your app needs to start

          echo "Checking health endpoint..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Health check passed with status 200!"
            exit 0
          else
            echo "Health check failed with status $RESPONSE"
            exit 1
