name: Webapp CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}  
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}  
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   env:
      #     DATABASE_URL: postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}
      #     PORT: ${{ secrets.PORT }} 
      #   run: npm test
      - name: Echo Secrets for Debugging (USE WITH CAUTION)
        run: |
          echo "DB_USERNAME: ${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
          echo "DB_NAME: ${{ secrets.DB_NAME }}"
          echo "PORT: ${{ secrets.PORT }}"
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}
      # - name: Build the application
      #   run: npm run build

      # - name: Start the application
      #   env:
      #     PORT: ${{ secrets.PORT }} 
      #   run: npm start  
